#!/bin/sh

set -eu

exec 2>&1

COMMAND=/usr/sbin/nginx
PID_FILE=/run/nginx/nginx.pid

install -d -o nginx -g nginx ${PID_FILE%/*}
exec ${COMMAND} -c /etc/nginx/nginx.conf -g "pid $PID_FILE; daemon off;"
