#!/bin/sh

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ -f "${PHP_INI_DIR}/conf.d/xdebug.ini" ]; then
    mode="${1:-"debug,coverage"}"
    sed -i "s/^xdebug\\.mode.*\$/xdebug.mode = ${mode}/" "${PHP_INI_DIR}/conf.d/xdebug.ini"
    sv restart php-fpm
    echo "xdebug.mode set to ${mode}"
else
    echo "Unable to find ${PHP_INI_DIR}/conf.d/xdebug.ini"
    exit 1
fi
